%define	rbname	rdiscount

Summary:	Fast Implementation of Gruber's Markdown in C
Name:		rubygem-%{rbname}

Version:	2.2.0.2
Release:	1
Group:		Development/Ruby
License:	BSD
URL:		http://github.com/davidfstr/rdiscount
Source0:	http://rubygems.org/gems/%{rbname}-%{version}.gem
BuildRequires:	rubygems 
BuildRequires:	ruby-devel

%description
Fast Implementation of Gruber's Markdown in C

%package	doc
Summary:	Documentation for %{name}
Group:		Books/Computer books
Requires:	%{name} = %{EVRD}
BuildArch:	noarch

%description	doc
Documents, RDoc & RI documentation for %{name}.

# FIXME why isn't this autogenerated?
%package debuginfo
Summary:	Debug info for %{name}
Group:		Debug
Requires:	%{name} = %{EVRD}

%description	debuginfo
Debug info for %{name}

%prep
%setup -q -c -T

%install
%gem_install -d %{buildroot} -n %{SOURCE0}

%files
%{_bindir}/rdiscount
%{_libdir}/ruby/gems/*/specifications/%{rbname}-%{version}.gemspec
%{_libdir}/ruby/gems/*/cache/%{rbname}-%{version}.gem
%{_libdir}/ruby/gems/*/gems/%{rbname}-%{version}
%{_libdir}/ruby/gems/*/extensions/*/*/%{rbname}-%{version}

%files doc
%doc %{_libdir}/ruby/gems/*/doc/%{rbname}-*

%files debuginfo
%{_prefix}/lib/debug%{_libdir}/ruby/gems/*/gems/%{rbname}-%{version}
%{_prefix}/lib/debug/.dwz/%{name}-*
%{_prefix}/lib/debug%{_libdir}/ruby/gems/*/extensions/*/*/%{rbname}-%{version}
